worker_processes auto;  # využije všetkých 16 jadier

events {
    worker_connections 4096;  # spojení na jeden worker proces
    multi_accept on;          # každý worker prijme naraz viac spojení
}

http {
    log_format gs '$time_iso8601 $remote_addr "$request" '
                  'status=$status rt=$request_time urt=$upstream_response_time';

    include       /etc/nginx/mime.types;
    default_type  application/octet-stream;

    sendfile        on;
    tcp_nopush      on;
    tcp_nodelay     on;
    keepalive_timeout 65;
    keepalive_requests 1000;

    include /etc/nginx/conf.d/*.conf;
}