"""
seed_tiles.py — Pre-seed GeoWebCache tiles for epis_wl75 and twl75 layers.

- Queries PostGIS for TIME + ELEVATION values from the last 14 days
- Sends GWC REST API seed requests for zoom levels 2-4, full world extent
- Truncates tiles older than 14 days to free cache space
- Warms the nginx proxy cache with the exact tile URLs browsers will send.
  BBOX strings are generated by the SAME pinned Leaflet build the frontend
  loads (scripts/vendor/leaflet-src.js) executed under Node — byte-identical
  by construction, guarded by a version assert against web/index.html and an
  empirical alignment check against real browser traffic in the access log.

Usage:
    python seed_tiles.py             # seed last 14 days, truncate old
    python seed_tiles.py --dry-run   # show what would be done, no requests
    python seed_tiles.py --truncate-only  # only remove old tiles
"""

from __future__ import annotations

import argparse
import concurrent.futures
import datetime
import json
import random
import re
import subprocess
import sys
import time
import urllib.parse
from collections import Counter

import psycopg2
import requests
from dotenv import load_dotenv

load_dotenv()

import os

# ─── Config ────────────────────────────────────────────────────────────────────
GEOSERVER_URL  = os.environ.get("GEOSERVER_URL",  "http://localhost:8080/geoserver")
GEOSERVER_USER = os.environ.get("GEOSERVER_USER", "admin")
GEOSERVER_PASS = os.environ.get("GEOSERVER_PASSWORD", "geoserver")
WORKSPACE      = os.environ.get("WORKSPACE", "E_and_T")

PG_HOST = os.environ.get("PG_HOST_LOCAL", "127.0.0.1")
PG_PORT = int(os.environ.get("PG_PORT", "5432"))
PG_DB   = os.environ.get("PG_DB",   "gis")
PG_USER = os.environ.get("PG_USER", "gisadmin")
PG_PASS = os.environ.get("PG_PASS", "geoserver")

LAYERS = ["epis_wl75", "twl75"]          # layers to seed
ZOOM_START  = 1
ZOOM_STOP   = 4
GRID_SET_ID = "EPSG:900913x2"            # Web Mercator x2 — matches Leaflet/GWC default
TILE_FORMAT = "image/png8"
THREAD_COUNT = 2                         # parallel GWC threads per seed job
PURGE_DAYS  = 14                         # truncate tiles older than N days

AUTH = (GEOSERVER_USER, GEOSERVER_PASS)

# ─── Nginx warm-up config ───────────────────────────────────────────────────────
NGINX_WARMUP_URL  = os.environ.get("NGINX_WARMUP_URL", "http://localhost")
READY_DATES_PATH  = os.environ.get("READY_DATES_PATH", "/opt/geoserver/web/ready_dates.json")
WARMUP_WORKERS    = 20                   # parallel curl-like requests for nginx warm-up
GWC_POLL_INTERVAL = 30                   # seconds between GWC status polls
GWC_TIMEOUT_MIN   = 30                   # max minutes to wait for GWC seeding

# ─── Leaflet-in-Node BBOX generation config ────────────────────────────────────
SCRIPT_DIR          = os.path.dirname(os.path.abspath(__file__))
LEAFLET_VENDOR_PATH = os.path.join(SCRIPT_DIR, "vendor", "leaflet-src.js")
INDEX_HTML_PATH     = os.environ.get("INDEX_HTML_PATH", "/opt/geoserver/web/index.html")
NGINX_ACCESS_LOG    = os.environ.get("NGINX_ACCESS_LOG", "/opt/geoserver/monitoring/nginx_logs/access.log")
WARMUP_SOURCE_IP    = os.environ.get("WARMUP_SOURCE_IP", "172.18.0.1")  # docker gateway = our own warm-up traffic
# SRS the PRODUCTION frontend sends (staging/develop currently sends EPSG:900913).
# Single source of truth for _build_tile_url and the URL-alignment tripwire —
# when promoting develop's frontend to production, update this value with it.
WARMUP_SRS          = os.environ.get("WARMUP_SRS", "EPSG:900913x2")

# Minimal browser shims so the real Leaflet build loads under plain Node.
_LEAFLET_NODE_SHIM = """
global.window = { devicePixelRatio: 1, screen: {} };
global.document = { documentElement: { style: {} }, createElement: function () { return { style: {} }; } };
global.navigator = { userAgent: 'node', platform: 'node' };
"""

# ─── PostGIS helpers ────────────────────────────────────────────────────────────

def get_db_conn():
    return psycopg2.connect(
        host=PG_HOST, port=PG_PORT,
        dbname=PG_DB, user=PG_USER, password=PG_PASS
    )


def get_recent_time_values(layer: str, days: int = 7) -> list[str]:
    """Return distinct ISO TIME strings from the last `days` days, newest first."""
    conn = get_db_conn()
    try:
        with conn.cursor() as cur:
            cur.execute(f"""
                SELECT DISTINCT ingestion
                FROM "{layer}"."{layer}"
                WHERE ingestion >= NOW() - INTERVAL '{days} days'
                ORDER BY ingestion DESC
            """)
            rows = cur.fetchall()
        return [row[0].strftime("%Y-%m-%dT%H:%M:%S.000Z") for row in rows]
    finally:
        conn.close()


def get_old_time_values(layer: str, before: datetime.datetime) -> list[str]:
    """Return distinct ISO TIME strings older than `before`."""
    conn = get_db_conn()
    try:
        with conn.cursor() as cur:
            cur.execute(f"""
                SELECT DISTINCT ingestion
                FROM "{layer}"."{layer}"
                WHERE ingestion < %s
                ORDER BY ingestion
            """, (before,))
            rows = cur.fetchall()
        return [row[0].strftime("%Y-%m-%dT%H:%M:%S.000Z") for row in rows]
    finally:
        conn.close()


def get_elevation_values(layer: str) -> list[str]:
    """Return distinct ELEVATION values for the given layer."""
    conn = get_db_conn()
    try:
        with conn.cursor() as cur:
            cur.execute(f"""
                SELECT DISTINCT elevation
                FROM "{layer}"."{layer}"
                ORDER BY elevation
            """)
            rows = cur.fetchall()
        return [str(int(row[0])) if row[0] == int(row[0]) else str(row[0]) for row in rows]
    finally:
        conn.close()


# ─── GWC REST helpers ───────────────────────────────────────────────────────────

def gwc_seed(layer: str, time_val: str, elev_val: str, seed_type: str = "seed", dry_run: bool = False) -> bool:
    """
    Send a seed or truncate request to GeoWebCache REST API.
    seed_type: 'seed' | 'reseed' | 'truncate'
    """
    full_layer = f"{WORKSPACE}:{layer}"
    url = f"{GEOSERVER_URL}/gwc/rest/seed/{full_layer}.json"

    body = {
        "seedRequest": {
            "name": full_layer,
            "bounds": {
                "coords": {"double": [-20037508.34, -20037508.34, 20037508.34, 20037508.34]}
            },
            "gridSetId": GRID_SET_ID,
            "zoomStart": ZOOM_START,
            "zoomStop": ZOOM_STOP,
            "format": TILE_FORMAT,
            "type": seed_type,
            "threadCount": THREAD_COUNT,
            "parameters": {
                "entry": [
                    {"string": ["TIME",      time_val]},
                    {"string": ["ELEVATION", elev_val]},
                    {"string": ["STYLES",    "E_and_T:VIDEO_WMS"]}
                ]
            }
        }
    }

    if dry_run:
        print(f"  [DRY-RUN] {seed_type.upper()} {full_layer} TIME={time_val} ELEV={elev_val}")
        return True

    try:
        r = requests.post(url, json=body, auth=AUTH, timeout=30)
        if r.status_code in (200, 202):
            return True
        else:
            print(f"  ⚠️  GWC {seed_type} failed ({r.status_code}): {r.text[:200]}")
            return False
    except Exception as e:
        print(f"  ❌ Request error: {e}")
        return False


def gwc_kill_all(layer: str) -> None:
    """Kill all running seed jobs for a layer."""
    full_layer = f"{WORKSPACE}:{layer}"
    url = f"{GEOSERVER_URL}/gwc/rest/seed/{full_layer}"
    try:
        requests.post(url, data="kill_all=all", auth=AUTH,
                      headers={"Content-Type": "application/x-www-form-urlencoded"},
                      timeout=10)
    except Exception:
        pass


# ─── GWC completion wait ────────────────────────────────────────────────────────

def wait_for_gwc_seeding(layer: str) -> bool:
    """
    Poll GWC REST API until all seed jobs for `layer` complete.
    Returns True if done within timeout, False if timeout exceeded.
    """
    full_layer = f"{WORKSPACE}:{layer}"
    url        = f"{GEOSERVER_URL}/gwc/rest/seed/{full_layer}.json"
    deadline   = time.time() + GWC_TIMEOUT_MIN * 60

    print(f"  ⏳ Waiting for GWC seeding to complete (max {GWC_TIMEOUT_MIN} min)...")
    while time.time() < deadline:
        try:
            r = requests.get(url, auth=AUTH, timeout=15)
            if r.status_code == 200:
                jobs = r.json().get("long-array-array", [])
                if not jobs:
                    print(f"  ✅ GWC seeding complete for {layer}")
                    return True
                # jobs: [tilesProcessed, tilesTotal, tilesRemaining, numThreads, taskId]
                remaining = sum(j[2] for j in jobs if len(j) > 2)
                print(f"  ⏳ {len(jobs)} job(s) active, ~{remaining:,} tiles remaining...")
            else:
                print(f"  ⚠️  GWC poll returned HTTP {r.status_code}")
        except Exception as exc:
            print(f"  ⚠️  GWC poll error: {exc}")
        time.sleep(GWC_POLL_INTERVAL)

    print(f"  ❌ GWC seeding timeout after {GWC_TIMEOUT_MIN} min for {layer}")
    return False


# ─── Nginx warm-up ─────────────────────────────────────────────────────────────

def get_vendored_leaflet_version() -> str | None:
    """Load the vendored Leaflet under Node and return its L.version."""
    try:
        result = subprocess.run(
            ['node', '-e', _LEAFLET_NODE_SHIM +
             f"process.stdout.write(require({json.dumps(LEAFLET_VENDOR_PATH)}).version);"],
            capture_output=True, text=True, timeout=30
        )
        if result.returncode == 0 and result.stdout.strip():
            return result.stdout.strip()
        print(f"  ⚠️  Could not read vendored Leaflet version: {result.stderr[:200]}")
    except Exception as exc:
        print(f"  ⚠️  Could not read vendored Leaflet version: {exc}")
    return None


def get_frontend_leaflet_version() -> str | None:
    """Parse the pinned leaflet@X.Y.Z from the frontend's index.html."""
    candidates = [INDEX_HTML_PATH, os.path.join(SCRIPT_DIR, "..", "web", "index.html")]
    for path in candidates:
        try:
            with open(path) as f:
                html = f.read()
        except OSError:
            continue
        m = re.search(r'leaflet@(\d+\.\d+\.\d+)/dist/leaflet(?:-src)?\.js', html)
        if m:
            return m.group(1)
    return None


def assert_leaflet_version_alignment() -> None:
    """
    Refuse to warm the cache with a Leaflet build different from the frontend's.

    The nginx cache key is the exact request URI, and our warm-up bbox strings
    are byte-for-byte Leaflet output — so a frontend Leaflet upgrade without a
    matching scripts/vendor/leaflet-src.js update is exactly how the two would
    silently drift apart again (hand-rolled math vs leaflet@1.9.4 previously
    left ~87% of warm-up writing cache keys no browser ever requested).
    Fail loudly BEFORE truncating/seeding anything.
    """
    frontend = get_frontend_leaflet_version()
    vendored = get_vendored_leaflet_version()

    if vendored is None:
        raise RuntimeError(
            f"Cannot load vendored Leaflet ({LEAFLET_VENDOR_PATH}) under Node — "
            f"aborting before any seeding. Warm-up without it would write useless cache keys."
        )
    if frontend is None:
        print(f"  ⚠️  Could not determine frontend Leaflet version from index.html — "
              f"proceeding with vendored {vendored}, but verify manually")
        return
    if frontend != vendored:
        raise RuntimeError(
            f"Leaflet version mismatch: frontend index.html pins {frontend}, "
            f"scripts/vendor/leaflet-src.js is {vendored}. Warm-up bbox strings would "
            f"not match browser URLs → every warmed tile would be a dead cache entry. "
            f"Fix: update scripts/vendor/leaflet-src.js to leaflet@{frontend} "
            f"(https://unpkg.com/leaflet@{frontend}/dist/leaflet-src.js)."
        )
    print(f"  ✅ Leaflet version aligned: frontend == vendored == {vendored}")


def compute_tile_bboxes() -> list[tuple]:
    """
    Compute every tile BBOX string for gridset zoom ZOOM_START–ZOOM_STOP by
    executing the SAME pinned Leaflet build the frontend loads
    (scripts/vendor/leaflet-src.js) under Node.js, walking the browser's exact
    code path for a 512-px WMS tile:

        GridLayer._tileCoordsToNwSe:  nwPoint = coords.scaleBy(512)
                                      map.unproject(nwPoint, z)  = crs.pointToLatLng
        TileLayer.WMS.getTileUrl:     bounds(crs.project(nw), crs.project(se))
                                      [min.x, min.y, max.x, max.y].join(',')

    The bbox string is formed INSIDE JS (same float→string serialization as the
    browser), so it is byte-identical to real browser URLs by construction —
    validated empirically at 100% against live traffic (2026-07-10).

    Gridset EPSG:900913x2 level z has 2^z columns of 512-px tiles, i.e. world
    width 512·2^z px = crs.scale(z+1) → the matching Leaflet map zoom is z+1.

    Returns list of (gridset_zoom, col, row, bbox_str).

    No fallback: hand-rolled float replicas are exactly the drift this design
    replaces, so if Node or the vendored Leaflet is unavailable we raise
    instead of silently warming cache keys nobody will ever hit.
    """
    if not os.path.exists(LEAFLET_VENDOR_PATH):
        raise RuntimeError(f"Vendored Leaflet not found: {LEAFLET_VENDOR_PATH}")

    js_code = (_LEAFLET_NODE_SHIM + """
const L = require(__LEAFLET_PATH__);
const crs = L.CRS.EPSG3857;
const TILE = 512;
const out = [];
for (let z = __ZOOM_START__; z <= __ZOOM_STOP__; z++) {
    const leafletZoom = z + 1;   // crs.scale(z+1) = 256*2^(z+1) = 512*2^z
    const n = 1 << z;
    for (let col = 0; col < n; col++) {
        for (let row = 0; row < n; row++) {
            const nw = crs.pointToLatLng(L.point(col * TILE, row * TILE), leafletZoom);
            const se = crs.pointToLatLng(L.point((col + 1) * TILE, (row + 1) * TILE), leafletZoom);
            const b = L.bounds(crs.project(nw), crs.project(se));
            out.push([z, col, row, [b.min.x, b.min.y, b.max.x, b.max.y].join(',')]);
        }
    }
}
process.stdout.write(JSON.stringify(out));
"""
    ).replace("__LEAFLET_PATH__", json.dumps(LEAFLET_VENDOR_PATH)) \
     .replace("__ZOOM_START__", str(ZOOM_START)) \
     .replace("__ZOOM_STOP__", str(ZOOM_STOP))

    result = subprocess.run(['node', '-e', js_code],
                            capture_output=True, text=True, timeout=60)
    if result.returncode != 0 or not result.stdout:
        raise RuntimeError(f"Leaflet BBOX generation failed (rc={result.returncode}): "
                           f"{result.stderr[:300]}")

    bboxes = [tuple(item) for item in json.loads(result.stdout)]
    print(f"  ✅ {len(bboxes)} tile BBOXes generated via vendored Leaflet under Node")
    return bboxes


def _build_tile_url(layer: str, time_val: str, elev_val: str, bbox_str: str) -> str:
    """
    Build the exact tile URL the production browser (Leaflet) sends.

    IMPORTANT: bbox commas must be literal, NOT percent-encoded (%2C).
    Nginx cache key = "$request_method$request_uri" (full URI string). Leaflet
    sends raw commas in bbox, so we must do the same — using requests' params=
    would encode them as %2C and the cache keys would never match.

    CRITICAL: parameter ORDER must byte-match the browser's. Measured from live
    production traffic (2026-07-10, 4897/4901 requests):
      service, request, layers, styles, format, transparent, version,
      time, elevation, tiled, SRS, srs, width, height  [bbox appended last]
    A previous version had layers/time/elevation in a different position —
    every warm-up request wrote a cache key no browser ever hit, even though
    the bbox strings were already byte-identical. Any drift here is now caught
    by verify_browser_url_alignment(), which rebuilds real logged browser URIs
    through THIS function and requires byte equality.

    bbox_str is used VERBATIM — it was serialized inside Leaflet-under-Node
    (compute_tile_bboxes), so no Python float formatting may touch it.
    """
    qs = urllib.parse.urlencode({
        'service':     'WMS',
        'request':     'GetMap',
        'layers':      f'{WORKSPACE}:{layer}',
        'styles':      '',
        'format':      'image/png8',
        'transparent': 'true',
        'version':     '1.1.1',
        'time':        time_val,
        'elevation':   elev_val,
        'tiled':       'true',
        'SRS':         WARMUP_SRS,
        'srs':         'EPSG:3857',
        'width':       '512',
        'height':      '512',
    })
    return f"{NGINX_WARMUP_URL}/geoserver/gwc/service/wms?{qs}&bbox={bbox_str}"


def _warmup_single(session: requests.Session, layer: str,
                   time_val: str, elev_val: str, bbox: tuple) -> bool:
    """Fire one nginx warmup request. bbox = (z, col, row, bbox_str). True on HTTP 200."""
    url = _build_tile_url(layer, time_val, elev_val, bbox[3])
    try:
        r = session.get(url, timeout=30)
        return r.status_code == 200
    except Exception:
        return False


def run_nginx_warmup(layer: str, time_vals: list[str], elev_vals: list[str],
                     bboxes: list[tuple], dry_run: bool = False) -> bool:
    """
    Warm nginx proxy cache for every tile × time × elevation combination.
    Uses a thread pool (WARMUP_WORKERS) so all tiles fly in parallel.
    `bboxes` comes from compute_tile_bboxes() — computed once by the caller.
    Returns True if all requests succeeded.
    """
    total_tiles = len(time_vals) * len(elev_vals) * len(bboxes)

    if dry_run:
        print(f"  [DRY-RUN] WARMUP {layer}: "
              f"{len(time_vals)} time(s) × {len(elev_vals)} elev(s) "
              f"× {len(bboxes)} tiles = {total_tiles} requests")
        return True

    print(f"  🔥 Nginx warmup: {len(time_vals)} time(s) × {len(elev_vals)} elev(s) "
          f"× {len(bboxes)} tiles = {total_tiles} requests")

    tasks: list[tuple] = [
        (t, e, b)
        for t in time_vals
        for e in elev_vals
        for b in bboxes
    ]

    done = errors = 0
    session = requests.Session()
    session.headers.update({'Connection': 'keep-alive'})

    with concurrent.futures.ThreadPoolExecutor(max_workers=WARMUP_WORKERS) as pool:
        futs = {
            pool.submit(_warmup_single, session, layer, t, e, b): (t, e, b)
            for t, e, b in tasks
        }
        for fut in concurrent.futures.as_completed(futs):
            done += 1
            if not fut.result():
                errors += 1
            if done % 200 == 0 or done == total_tiles:
                sys.stdout.write(f"\r     Progress: {done}/{total_tiles} ({errors} errors)")
                sys.stdout.flush()

    print(f"\n  ✅ Nginx warmup done: {done - errors}/{done} tiles cached")
    return errors == 0


# ─── Cache verification ─────────────────────────────────────────────────────────

CACHE_VERIFY_SAMPLE_SIZE   = 20     # tiles to re-check per layer after warm-up
CACHE_VERIFY_MIN_HIT_RATIO = 0.90   # warn if fewer than 90% come back as HIT


def _verify_single(session: requests.Session, layer: str,
                   time_val: str, elev_val: str, bbox: tuple) -> str:
    """Re-request one just-warmed tile and return its X-Cache-Status header."""
    url = _build_tile_url(layer, time_val, elev_val, bbox[3])
    try:
        r = session.get(url, timeout=30)
        return r.headers.get('X-Cache-Status', 'MISSING-HEADER')
    except Exception as exc:
        return f'ERROR:{type(exc).__name__}'


def verify_nginx_warmup(layer: str, time_vals: list[str], elev_vals: list[str],
                        bboxes: list[tuple],
                        sample_size: int = CACHE_VERIFY_SAMPLE_SIZE,
                        dry_run: bool = False) -> bool:
    """
    Re-request a random sample of tiles that run_nginx_warmup() just fetched,
    and check their X-Cache-Status response header.

    This confirms nginx actually WROTE the cache entries (writability, zone
    capacity, eviction). It cannot detect drift from the browser on its own —
    it re-requests our own URLs — which is why verify_browser_url_alignment()
    exists as the second, independent check against real user traffic.

    Returns True if the sampled hit ratio meets CACHE_VERIFY_MIN_HIT_RATIO.
    """
    population = [(t, e, b) for t in time_vals for e in elev_vals for b in bboxes]
    if not population:
        return True

    sample = random.sample(population, min(sample_size, len(population)))

    if dry_run:
        print(f"  [DRY-RUN] Would verify {len(sample)} sample tile(s) for {layer}")
        return True

    session = requests.Session()
    session.headers.update({'Connection': 'keep-alive'})

    statuses = [_verify_single(session, layer, t, e, b) for t, e, b in sample]
    counts = Counter(statuses)
    hits = counts.get('HIT', 0)
    ratio = hits / len(statuses)

    print(f"  🔍 Cache verify {layer}: {hits}/{len(statuses)} HIT ({ratio:.0%})  "
          f"breakdown={dict(counts)}")

    if ratio < CACHE_VERIFY_MIN_HIT_RATIO:
        print(f"  ⚠️  WARNING: {layer} hit ratio {ratio:.0%} is below the "
              f"{CACHE_VERIFY_MIN_HIT_RATIO:.0%} threshold — warm-up requests may not "
              f"be matching real browser cache keys (BBOX/param drift), or nginx is "
              f"evicting tiles faster than expected. Check the Grafana "
              f"'Nginx GWC Cache Hit Ratio' dashboard.")
        return False

    return True


BROWSER_ALIGN_TAIL_LINES = 300000   # how much recent access log to sample
BROWSER_ALIGN_MIN_RATIO  = 0.90     # warn if <90% of browser URIs rebuild byte-identically


def verify_browser_url_alignment(bboxes: list[tuple]) -> bool | None:
    """
    The drift detector: prove that _build_tile_url() produces byte-for-byte the
    same URIs real browsers send, using the nginx access log as ground truth.

    For every recent real-browser GWC GetMap request (own warm-up IP excluded,
    png8 + production-shape only), it parses out layer/time/elevation/bbox and
    REBUILDS the URI through _build_tile_url(). The rebuilt string must equal
    the logged one exactly — the nginx cache key is "$request_method$request_uri",
    so equality here is equality of cache keys.

    History of why this is strict: bbox-only comparison previously reported
    100% aligned while the PARAMETER ORDER was wrong (layers/time/elevation in
    a different position), so every warm-up request still wrote a dead cache
    key. Full-URI rebuild-equality has no such blind spot: any param reorder,
    SRS/format/width change, or encoding difference fails it immediately.

    Returns True (aligned), False (misaligned → warn), or None (no comparable
    browser traffic in the log).
    """
    generated_bboxes = {b[3] for b in bboxes}

    try:
        result = subprocess.run(
            ['tail', '-n', str(BROWSER_ALIGN_TAIL_LINES), NGINX_ACCESS_LOG],
            capture_output=True, text=True, timeout=60
        )
        lines = result.stdout.splitlines()
    except Exception as exc:
        print(f"  ⚠️  Browser-alignment check skipped (cannot read access log): {exc}")
        return None

    uri_re = re.compile(r'"GET (\S+) HTTP')
    prefix_len = len(NGINX_WARMUP_URL)
    total = matched = 0
    mismatch_samples: list[tuple[str, str]] = []
    known_layers = set(LAYERS)
    srs_seen: Counter = Counter()   # which SRS shapes real browsers actually send

    for line in lines:
        if 'gwc/service/wms' not in line or 'request=GetMap' not in line:
            continue
        fields = line.split()
        if len(fields) < 2 or fields[1] == WARMUP_SOURCE_IP:
            continue  # skip our own warm-up traffic — that's the self-reference trap
        m = uri_re.search(line)
        if not m:
            continue
        uri = m.group(1)
        try:
            query = uri.split('?', 1)[1]
            params = dict(urllib.parse.parse_qsl(query, keep_blank_values=True))
        except (IndexError, ValueError):
            continue
        if params.get('format') != 'image/png8':
            continue  # plain-png side path isn't warmed; don't count it against alignment
        srs_seen[params.get('SRS', '?')] += 1
        if params.get('SRS') != WARMUP_SRS:
            continue  # e.g. staging/develop frontend (SRS=EPSG:900913) — deliberately not warmed
        layer = params.get('layers', '')
        if not layer.startswith(f'{WORKSPACE}:'):
            continue
        layer = layer.split(':', 1)[1]
        if layer not in known_layers:
            continue
        raw_bbox = re.search(r'(?:\?|&)bbox=([^&]*)', uri)
        if not raw_bbox:
            continue
        bbox_str = raw_bbox.group(1)
        if bbox_str not in generated_bboxes:
            continue  # deeper zoom than we seed — browser renders on the fly, not our key space
        if 'time' not in params or 'elevation' not in params:
            continue

        rebuilt = _build_tile_url(layer, params['time'], params['elevation'], bbox_str)
        rebuilt_uri = rebuilt[prefix_len:]  # strip http://localhost — compare path?query only

        total += 1
        if rebuilt_uri == uri:
            matched += 1
        elif len(mismatch_samples) < 2:
            mismatch_samples.append((uri, rebuilt_uri))

    # Frontend-promotion tripwire: if most real tile traffic uses a different SRS
    # shape than we warm, the frontend URL shape changed under us (e.g. develop
    # with SRS=EPSG:900913 was promoted to production) and the warm-up is dead.
    # Without this, such a flip would silently reduce this check to "no data".
    if srs_seen:
        dominant, dom_count = srs_seen.most_common(1)[0]
        if dominant != WARMUP_SRS:
            print(f"  ⚠️  WARNING: dominant real-browser SRS is '{dominant}' "
                  f"({dom_count}/{sum(srs_seen.values())} png8 tile requests) but warm-up sends "
                  f"'{WARMUP_SRS}' — the frontend URL shape has changed (develop promoted to "
                  f"production?). Update _build_tile_url to the new shape; until then the "
                  f"warm-up caches keys nobody requests. Shapes seen: {dict(srs_seen)}")
            return False

    if total == 0:
        print("  ℹ️  Browser-alignment check: no comparable real-browser GWC traffic in log — nothing to verify")
        return None

    ratio = matched / total
    print(f"  🔍 Browser URL alignment: {matched}/{total} real-browser URIs rebuild "
          f"byte-identically through _build_tile_url ({ratio:.0%})")

    if ratio < BROWSER_ALIGN_MIN_RATIO:
        print(f"  ⚠️  WARNING: warm-up URIs diverge from real browser URIs "
              f"(ratio {ratio:.0%} < {BROWSER_ALIGN_MIN_RATIO:.0%}) — warm-up is writing cache "
              f"keys browsers don't request. Compare and fix _build_tile_url:")
        for browser_uri, our_uri in mismatch_samples:
            print(f"       browser: {browser_uri[:200]}")
            print(f"       rebuilt: {our_uri[:200]}")
        return False

    return True


# ─── Ready-dates JSON ──────────────────────────────────────────────────────────

def write_ready_dates(all_seeded_times: list[str], dry_run: bool = False) -> None:
    """
    Merge newly seeded dates with any existing ready_dates.json,
    drop dates older than PURGE_DAYS, and write the file.
    The frontend reads this to block dates that are not yet fully cached.
    """
    now    = datetime.datetime.now(datetime.timezone.utc).replace(tzinfo=None)
    cutoff = now - datetime.timedelta(days=PURGE_DAYS)

    # Convert timestamps to YYYY-MM-DD date strings
    new_date_strs: set[str] = set()
    for t in all_seeded_times:
        try:
            d = datetime.datetime.fromisoformat(t.replace('Z', '+00:00')).date()
            if datetime.datetime.combine(d, datetime.time()) >= cutoff:
                new_date_strs.add(str(d))
        except ValueError:
            pass

    # Merge with existing ready dates (if any)
    existing: list[str] = []
    try:
        with open(READY_DATES_PATH) as f:
            existing = json.load(f).get("ready_dates", [])
    except FileNotFoundError:
        pass
    except Exception as exc:
        print(f"  ⚠️  Could not read existing {READY_DATES_PATH}: {exc}")

    # Keep existing dates that are still within the purge window
    for d in existing:
        try:
            if datetime.date.fromisoformat(d) >= cutoff.date():
                new_date_strs.add(d)
        except ValueError:
            pass

    ready = sorted(new_date_strs)
    data  = {
        "ready_dates": ready,
        "updated_at":  now.strftime("%Y-%m-%dT%H:%M:%S.000Z"),
    }

    if dry_run:
        print(f"  [DRY-RUN] Would write {READY_DATES_PATH}: {ready}")
        return

    try:
        with open(READY_DATES_PATH, 'w') as f:
            json.dump(data, f, indent=2)
        print(f"  ✅ {READY_DATES_PATH} updated — {len(ready)} ready date(s): {ready}")
    except Exception as exc:
        print(f"  ❌ Failed to write {READY_DATES_PATH}: {exc}")


# ─── Main logic ────────────────────────────────────────────────────────────────

def run_seed(dry_run: bool = False, truncate_only: bool = False, days: int = 7):
    now    = datetime.datetime.now(datetime.timezone.utc).replace(tzinfo=None)
    before = now - datetime.timedelta(days=PURGE_DAYS)

    print(f"\n{'='*60}")
    print(f"  GWC Tile Seeder + Nginx Warm-up")
    print(f"  Mode     : {'DRY RUN' if dry_run else 'LIVE'}")
    print(f"  Layers   : {LAYERS}")
    print(f"  Zoom     : {ZOOM_START}–{ZOOM_STOP}")
    print(f"  Seed     : last {days} day(s)")
    print(f"  Purge old: > {PURGE_DAYS} days (before {before.strftime('%Y-%m-%d')})")
    print(f"{'='*60}\n")

    # ── Phase 0: self-checks — fail loudly BEFORE truncating anything ─────
    # If the Leaflet build is misaligned or Node can't generate bboxes, warming
    # would write dead cache keys; better to abort with old tiles still cached.
    bboxes: list[tuple] = []
    if not truncate_only:
        print("🔎 Phase 0 — self-checks")
        assert_leaflet_version_alignment()          # raises on version mismatch
        bboxes = compute_tile_bboxes()              # raises if node/vendor broken
        print()

    # Collect seeded times per layer so we can warm-up and update ready_dates.json
    seeded_data: dict[str, tuple[list[str], list[str]]] = {}  # layer -> (times, elevs)

    # ── Phase 1: GWC truncate + seed (submit jobs) ─────────────────────────
    for layer in LAYERS:
        print(f"📦 Layer: {layer}")

        # 1a. Truncate old tiles
        try:
            old_times = get_old_time_values(layer, before)
        except Exception as e:
            print(f"  ⚠️  Could not query old TIME values: {e}")
            old_times = []

        if old_times:
            try:
                elevations = get_elevation_values(layer)
            except Exception as e:
                print(f"  ⚠️  Could not query ELEVATION values: {e}")
                elevations = ["0"]

            print(f"  🗑️  Truncating {len(old_times)} old TIME value(s) × {len(elevations)} elevation(s)...")
            truncated = 0
            for t in old_times:
                for e in elevations:
                    if gwc_seed(layer, t, e, seed_type="truncate", dry_run=dry_run):
                        truncated += 1
            print(f"  ✅ Truncated {truncated} combination(s)")
        else:
            print(f"  ℹ️  No old tiles to truncate")

        if truncate_only:
            continue

        # 1b. Seed last N days
        try:
            recent_times = get_recent_time_values(layer, days=days)
        except Exception as e:
            print(f"  ⚠️  Could not query recent TIME values: {e}")
            recent_times = []

        if not recent_times:
            print(f"  ℹ️  No TIME values found in last {days} days — skipping seed")
            continue

        try:
            elevations = get_elevation_values(layer)
        except Exception as e:
            print(f"  ⚠️  Could not query ELEVATION values: {e}")
            elevations = ["0"]

        total = len(recent_times) * len(elevations)
        print(f"  🌱 Seeding {len(recent_times)} TIME value(s) × {len(elevations)} elevation(s) = {total} job(s)")
        print(f"     TIMEs      : {recent_times}")
        print(f"     ELEVATIONs : {elevations}")

        seeded = 0
        for t in recent_times:
            for elv in elevations:
                if gwc_seed(layer, t, elv, seed_type="seed", dry_run=dry_run):
                    seeded += 1
                    sys.stdout.write(f"\r     Progress: {seeded}/{total}")
                    sys.stdout.flush()
                time.sleep(0.1)

        print(f"\n  ✅ Submitted {seeded}/{total} seed job(s)")
        seeded_data[layer] = (recent_times, elevations)

    if truncate_only:
        print(f"\n{'='*60}")
        print("  Truncate-only mode — skipping GWC wait and nginx warm-up.")
        print(f"{'='*60}\n")
        return

    if not seeded_data:
        print(f"\n{'='*60}")
        print("  No layers were seeded — skipping warm-up and ready_dates update.")
        print(f"{'='*60}\n")
        return

    # ── Phase 2: Wait for GWC to finish, then warm nginx ──────────────────
    all_seeded_times: list[str] = []
    gwc_failed = False
    verify_failed = False

    for layer, (recent_times, elevations) in seeded_data.items():
        print(f"\n🕐 Phase 2 — {layer}")

        gwc_ok = wait_for_gwc_seeding(layer)
        if not gwc_ok:
            gwc_failed = True
            print(f"  ⚠️  GWC timeout for {layer} — skipping nginx warm-up for this layer")
            continue

        run_nginx_warmup(layer, recent_times, elevations, bboxes, dry_run=dry_run)
        all_seeded_times.extend(recent_times)

        if not verify_nginx_warmup(layer, recent_times, elevations, bboxes, dry_run=dry_run):
            verify_failed = True

    # Independent drift check: do real browsers agree with our cache keys?
    if all_seeded_times and not dry_run:
        if verify_browser_url_alignment(bboxes) is False:
            verify_failed = True

    # ── Phase 3: Write ready_dates.json ───────────────────────────────────
    print(f"\n📋 Phase 3 — ready_dates.json")
    if all_seeded_times:
        write_ready_dates(all_seeded_times, dry_run=dry_run)
    else:
        print("  ⚠️  No layers completed warm-up — ready_dates.json not updated")

    print(f"\n{'='*60}")
    if gwc_failed:
        print("  ⚠️  Finished with GWC timeout(s). Check GeoServer logs.")
    elif verify_failed:
        print("  ⚠️  Finished, but cache verification found a low hit ratio for at")
        print("      least one layer — see the warning(s) above. This does NOT fail")
        print("      the run (seeding itself succeeded); check the Grafana cache")
        print("      dashboard and this log if tiles feel slow after this run.")
    else:
        print("  ✅ GWC seeding + nginx warm-up complete. Cache verification OK.")
    print(f"{'='*60}\n")


# ─── Entry point ───────────────────────────────────────────────────────────────

if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="Pre-seed GWC tiles for video WMS layers")
    parser.add_argument("--dry-run",       action="store_true", help="Print actions without sending requests")
    parser.add_argument("--truncate-only", action="store_true", help="Only truncate old tiles, skip seeding")
    parser.add_argument("--days",          type=int, default=14, help="How many days back to seed (default: 14)")
    args = parser.parse_args()

    run_seed(dry_run=args.dry_run, truncate_only=args.truncate_only, days=args.days)
